# Generated by Django 2.2.1 on 2019-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau_quiz', '0004_player_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='static/img/chicken.PNG', upload_to='images/'),
        ),
    ]
