# Generated by Django 2.2.1 on 2019-05-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau_quiz', '0005_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='chicken.PNG', upload_to='images/'),
        ),
    ]
